(let ((id (lambda (x) x)))
  (let ((blur (lambda (y) y)))
    (letrec ((lp (lambda (a n)
                   (if (<= n 1)
                       (id a)
                       (let ((r ((blur id) #t)))
                         (let ((s ((blur id) #f)))
                           (not ((blur lp) s (- n 1)))))))))
      (lp #f 2))))